version: "3.9"

services:
    mysqldb:
      image: mysql:8
      restart: unless-stopped
      container_name: mysqldb
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootroot
        MYSQL_DATABASE: db_patient
      volumes:
        - sql-data:/var/lib/mysql
      networks:
          - mediscreen_network

    patient:
      build: ./mediPatient/.
      image: patient
      container_name: patient
      depends_on:
        - mysqldb
      ports:
        - "8081:8081"
      environment:
        MYSQL_DATABASE: db_patient
        MYSQL_URL: mysqldb
        MYSQL_USER: root
        MYSQL_PASSWORD: rootroot
      networks:
        - mediscreen_network
      restart: on-failure

    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb:/data/db
      networks:
        - mediscreen_network

    note:
        build: ./mediNote/.
        image: note
        container_name: note
        environment:
          PATIENT_URL: patient:8081
          MONGODB_HOST: mongodb
          MONGODB_PORT: 27017
          MONGODB_DB: note
        depends_on:
          - mongodb
          - patient
        ports:
          - "8082:8082"
        networks:
          - mediscreen_network

    assessment:
        build: ./mediAssessment/.
        image: assessment
        container_name: assessment
        environment:
          FEIGN_MEDIPATIENT_URL: patient:8081
          FEIGN_MEDINOTE_URL: note:8082
        depends_on:
          - note
          - patient
        ports:
          - "8080:8080"
        networks:
          - mediscreen_network
    ui:
      build: ./mediClientUI/.
      image: client_ui
      container_name: client_ui
      depends_on:
        - note
        - patient
        - assessment
      environment:
        FEIGN_MEDIPATIENT_URL: patient:8081
        FEIGN_MEDINOTE_URL: note:8082
        FEIGN_MEDIASSESSMENT_URL: assessment:8080
      ports:
        - "8090:8090"
      networks:
        - mediscreen_network
networks:
    mediscreen_network:
      driver: bridge
volumes:
  sql-data:
  mongodb: